model_func: resnet18
data_format:
  - Numpy arrays
  - Image files
gpu:
  - True
  - False
checkpoint:
  - True
  - False
visualization_tool:
  - Not at all
  - Tensorboard
  - Aim
  # TODO: Find a way to add comet.ml here, without requiring API key.
pretrained: False
loss: CrossEntropyLoss
optimizer: Adam
num_classes: 10
lr: 0.001
batch_size: 128
num_epochs: 1
print_every: 1
